project_id = "awrduehwnyxbwtjbbrhw"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15

[functions.secure-file-upload]
verify_jwt = true

[functions.store-classified-document]
verify_jwt = true

[functions.sync-accounts]
verify_jwt = true

[functions.export-approved-invoices]
verify_jwt = true

[functions.test-webhook]
verify_jwt = false

[functions.notify-admin-new-user]
verify_jwt = false