// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awrduehwnyxbwtjbbrhw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3cmR1ZWh3bnl4Ynd0amJicmh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MTA3NzQsImV4cCI6MjA2ODA4Njc3NH0.D9qdE99x88EKAFJxRHbseuaphVlncOGyICMbd1vZUSw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});